namespace SDG.Unturned;

public enum ENPCConditionType
{
    NONE,
    EXPERIENCE,
    REPUTATION,
    FLAG_BOOL,
    FLAG_SHORT,
    QUEST,
    SKILLSET,
    ITEM,
    KILLS_ZOMBIE,
    KILLS_HORDE,
    KILLS_ANIMAL,
    COMPARE_FLAGS,
    TIME_OF_DAY,
    PLAYER_LIFE_HEALTH,
    PLAYER_LIFE_FOOD,
    PLAYER_LIFE_WATER,
    PLAYER_LIFE_VIRUS,
    HOLIDAY,
    KILLS_PLAYER,
    KILLS_OBJECT,
    CURRENCY,
    KILLS_TREE,
    WEATHER_STATUS,
    WEATHER_BLEND_ALPHA,
    IS_FULL_MOON,
    DATE_COUNTER,
    PLAYER_LIFE_STAMINA
}
