namespace SDG.Unturned;

public enum ENPCRewardType
{
    NONE,
    EXPERIENCE,
    REPUTATION,
    FLAG_BOOL,
    FLAG_SHORT,
    FLAG_SHORT_RANDOM,
    QUEST,
    ITEM,
    ITEM_RANDOM,
    ACHIEVEMENT,
    VEHICLE,
    TELEPORT,
    EVENT,
    FLAG_MATH,
    CURRENCY,
    HINT,
    PLAYER_SPAWNPOINT,
    PLAYER_LIFE_HEALTH,
    PLAYER_LIFE_FOOD,
    PLAYER_LIFE_WATER,
    PLAYER_LIFE_VIRUS,
    REWARDS_LIST_ASSET,
    CUTSCENE_MODE
}
