namespace SDG.Unturned;

public enum EPhysicsMaterial
{
    NONE,
    CLOTH_DYNAMIC,
    CLOTH_STATIC,
    TILE_DYNAMIC,
    TILE_STATIC,
    CONCRETE_DYNAMIC,
    CONCRETE_STATIC,
    FLESH_DYNAMIC,
    GRAVEL_DYNAMIC,
    GRAVEL_STATIC,
    METAL_DYNAMIC,
    METAL_STATIC,
    METAL_SLIP,
    WOOD_DYNAMIC,
    WOOD_STATIC,
    FOLIAGE_STATIC,
    FOLIAGE_DYNAMIC,
    SNOW_STATIC,
    ICE_STATIC,
    WATER_STATIC,
    ALIEN_DYNAMIC,
    SAND_STATIC
}
