namespace SDG.Unturned;

public enum EPlayerStat
{
    NONE,
    KILLS_ZOMBIES_NORMAL,
    KILLS_PLAYERS,
    FOUND_ITEMS,
    FOUND_RESOURCES,
    FOUND_EXPERIENCE,
    KILLS_ZOMBIES_MEGA,
    DEATHS_PLAYERS,
    KILLS_ANIMALS,
    FOUND_CRAFTS,
    FOUND_FISHES,
    FOUND_PLANTS,
    ACCURACY,
    HEADSHOTS,
    TRAVEL_FOOT,
    TRAVEL_VEHICLE,
    ARENA_WINS,
    FOUND_BUILDABLES,
    FOUND_THROWABLES
}
